"""add_rechtsform_and_medien_lizenz_tables

Revision ID: 0bcab5006983
Revises: e4db50debd03
Create Date: 2026-02-20 16:40:08.628340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bcab5006983'
down_revision: Union[str, Sequence[str], None] = 'e4db50debd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bas_medien_lizenz',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('kategorie', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medien_lizenz_kategorie', 'bas_medien_lizenz', ['kategorie'], unique=False)
    op.create_index(op.f('ix_bas_medien_lizenz_code'), 'bas_medien_lizenz', ['code'], unique=True)
    op.create_table('bas_rechtsform',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_lang', sa.String(length=200), nullable=True),
    sa.Column('land_code', sa.String(length=5), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rechtsform_land', 'bas_rechtsform', ['land_code'], unique=False)
    op.create_index(op.f('ix_bas_rechtsform_code'), 'bas_rechtsform', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bas_rechtsform_code'), table_name='bas_rechtsform')
    op.drop_index('idx_rechtsform_land', table_name='bas_rechtsform')
    op.drop_table('bas_rechtsform')
    op.drop_index(op.f('ix_bas_medien_lizenz_code'), table_name='bas_medien_lizenz')
    op.drop_index('idx_medien_lizenz_kategorie', table_name='bas_medien_lizenz')
    op.drop_table('bas_medien_lizenz')
    # ### end Alembic commands ###
