"""add einkaufskosten_usd to rch_auftrag

Revision ID: 0ec85ea7a1d8
Revises: 09150ae3af07
Create Date: 2026-02-17 09:14:00.231633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec85ea7a1d8'
down_revision: Union[str, Sequence[str], None] = '09150ae3af07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rch_auftrag', sa.Column('einkaufskosten_usd', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rch_auftrag', 'einkaufskosten_usd')
    # ### end Alembic commands ###
