"""add_hersteller_fields_to_unternehmen

Revision ID: 376057f71dd5
Revises: 0bcab5006983
Create Date: 2026-02-20 16:43:45.564846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376057f71dd5'
down_revision: Union[str, Sequence[str], None] = '0bcab5006983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('com_unternehmen', sa.Column('gruendungsjahr', sa.Integer(), nullable=True))
    op.add_column('com_unternehmen', sa.Column('gruender', sa.String(length=255), nullable=True))
    op.add_column('com_unternehmen', sa.Column('herkunftsland_id', sa.String(length=36), nullable=True))
    op.add_column('com_unternehmen', sa.Column('rechtsform_id', sa.String(length=36), nullable=True))
    op.add_column('com_unternehmen', sa.Column('gpsr_default_bevollmaechtigter_id', sa.String(length=36), nullable=True))
    op.create_index('idx_unternehmen_gpsr_bevollm', 'com_unternehmen', ['gpsr_default_bevollmaechtigter_id'], unique=False)
    op.create_index('idx_unternehmen_herkunftsland', 'com_unternehmen', ['herkunftsland_id'], unique=False)
    op.create_index('idx_unternehmen_rechtsform', 'com_unternehmen', ['rechtsform_id'], unique=False)
    op.create_foreign_key('fk_unternehmen_gpsr_bevollm', 'com_unternehmen', 'com_unternehmen', ['gpsr_default_bevollmaechtigter_id'], ['id'])
    op.create_foreign_key('fk_unternehmen_rechtsform', 'com_unternehmen', 'bas_rechtsform', ['rechtsform_id'], ['id'])
    op.create_foreign_key('fk_unternehmen_herkunftsland', 'com_unternehmen', 'geo_land', ['herkunftsland_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_unternehmen_herkunftsland', 'com_unternehmen', type_='foreignkey')
    op.drop_constraint('fk_unternehmen_rechtsform', 'com_unternehmen', type_='foreignkey')
    op.drop_constraint('fk_unternehmen_gpsr_bevollm', 'com_unternehmen', type_='foreignkey')
    op.drop_index('idx_unternehmen_rechtsform', table_name='com_unternehmen')
    op.drop_index('idx_unternehmen_herkunftsland', table_name='com_unternehmen')
    op.drop_index('idx_unternehmen_gpsr_bevollm', table_name='com_unternehmen')
    op.drop_column('com_unternehmen', 'gpsr_default_bevollmaechtigter_id')
    op.drop_column('com_unternehmen', 'rechtsform_id')
    op.drop_column('com_unternehmen', 'herkunftsland_id')
    op.drop_column('com_unternehmen', 'gruender')
    op.drop_column('com_unternehmen', 'gruendungsjahr')
    # ### end Alembic commands ###
