"""add_merge_config_tables

Revision ID: 4ab994ff485f
Revises: 75914bb61196
Create Date: 2026-02-15 20:36:22.407233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab994ff485f'
down_revision: Union[str, Sequence[str], None] = '75914bb61196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_import_file', sa.Column('file_role', sa.String(length=50), nullable=True))
    op.add_column('etl_import_file', sa.Column('merge_config_id', sa.String(length=36), nullable=True))
    op.add_column('etl_import_file', sa.Column('is_merged_output', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'etl_import_file', 'etl_merge_config', ['merge_config_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'etl_import_file', type_='foreignkey')
    op.drop_column('etl_import_file', 'is_merged_output')
    op.drop_column('etl_import_file', 'merge_config_id')
    op.drop_column('etl_import_file', 'file_role')
    # ### end Alembic commands ###
