"""Add plugin marketplace tables

Revision ID: 567197f4e309
Revises: bd831a7d434a
Create Date: 2026-01-17 17:44:41.741522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567197f4e309'
down_revision: Union[str, Sequence[str], None] = 'bd831a7d434a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plg_kategorie',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sortierung', sa.Integer(), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kategorie_sortierung', 'plg_kategorie', ['sortierung'], unique=False)
    op.create_index(op.f('ix_plg_kategorie_slug'), 'plg_kategorie', ['slug'], unique=True)
    op.create_table('plg_projekttyp',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('ist_kostenlos', sa.Boolean(), nullable=True),
    sa.Column('ist_testphase_erlaubt', sa.Boolean(), nullable=True),
    sa.Column('standard_testphase_tage', sa.Integer(), nullable=True),
    sa.Column('max_benutzer', sa.Integer(), nullable=True),
    sa.Column('max_api_calls_pro_monat', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sortierung', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projekttyp_sortierung', 'plg_projekttyp', ['sortierung'], unique=False)
    op.create_index(op.f('ix_plg_projekttyp_slug'), 'plg_projekttyp', ['slug'], unique=True)
    op.create_table('plg_plugin',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('beschreibung_kurz', sa.String(length=500), nullable=True),
    sa.Column('kategorie_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('version_datum', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dokumentation_url', sa.String(length=500), nullable=True),
    sa.Column('changelog_url', sa.String(length=500), nullable=True),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('min_api_version', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('plugin_json_hash', sa.String(length=64), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kategorie_id'], ['plg_kategorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plugin_kategorie', 'plg_plugin', ['kategorie_id'], unique=False)
    op.create_index('idx_plugin_status', 'plg_plugin', ['status'], unique=False)
    op.create_index(op.f('ix_plg_plugin_slug'), 'plg_plugin', ['slug'], unique=True)
    op.create_table('plg_plugin_version',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('ist_aktuell', sa.Boolean(), nullable=True),
    sa.Column('ist_breaking_change', sa.Boolean(), nullable=True),
    sa.Column('min_api_version', sa.String(length=20), nullable=True),
    sa.Column('veroeffentlicht_am', sa.DateTime(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plg_plugin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_version_aktuell', 'plg_plugin_version', ['plugin_id', 'ist_aktuell'], unique=False)
    op.create_index('idx_version_plugin', 'plg_plugin_version', ['plugin_id'], unique=False)
    op.create_index('uq_plugin_version', 'plg_plugin_version', ['plugin_id', 'version'], unique=True)
    op.create_table('plg_preis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('projekttyp_id', sa.String(length=36), nullable=False),
    sa.Column('modell', sa.String(length=20), nullable=False),
    sa.Column('preis', sa.Float(), nullable=False),
    sa.Column('waehrung', sa.String(length=3), nullable=True),
    sa.Column('staffel_ab_benutzer', sa.Integer(), nullable=True),
    sa.Column('staffel_preis', sa.Float(), nullable=True),
    sa.Column('preis_pro_api_call', sa.Float(), nullable=True),
    sa.Column('preis_pro_datensatz', sa.Float(), nullable=True),
    sa.Column('inkludierte_api_calls', sa.Integer(), nullable=True),
    sa.Column('einrichtungsgebuehr', sa.Float(), nullable=True),
    sa.Column('gueltig_ab', sa.DateTime(), nullable=True),
    sa.Column('gueltig_bis', sa.DateTime(), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plg_plugin.id'], ),
    sa.ForeignKeyConstraint(['projekttyp_id'], ['plg_projekttyp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_preis_aktiv', 'plg_preis', ['ist_aktiv'], unique=False)
    op.create_index('idx_preis_plugin', 'plg_preis', ['plugin_id'], unique=False)
    op.create_index('idx_preis_projekttyp', 'plg_preis', ['projekttyp_id'], unique=False)
    op.create_table('plg_projekt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projekttyp_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('kontakt_name', sa.String(length=255), nullable=True),
    sa.Column('kontakt_email', sa.String(length=255), nullable=True),
    sa.Column('kontakt_telefon', sa.String(length=50), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('geo_ort_id', sa.String(length=36), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=True),
    sa.Column('aktiviert_am', sa.DateTime(), nullable=True),
    sa.Column('deaktiviert_am', sa.DateTime(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['geo_ort_id'], ['geo_ort.id'], ),
    sa.ForeignKeyConstraint(['projekttyp_id'], ['plg_projekttyp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projekt_aktiv', 'plg_projekt', ['ist_aktiv'], unique=False)
    op.create_index('idx_projekt_geo', 'plg_projekt', ['geo_ort_id'], unique=False)
    op.create_index('idx_projekt_typ', 'plg_projekt', ['projekttyp_id'], unique=False)
    op.create_index(op.f('ix_plg_projekt_api_key_hash'), 'plg_projekt', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_plg_projekt_kontakt_email'), 'plg_projekt', ['kontakt_email'], unique=False)
    op.create_index(op.f('ix_plg_projekt_slug'), 'plg_projekt', ['slug'], unique=True)
    op.create_table('plg_lizenz',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projekt_id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=36), nullable=False),
    sa.Column('preis_id', sa.String(length=36), nullable=True),
    sa.Column('lizenz_start', sa.DateTime(), nullable=False),
    sa.Column('lizenz_ende', sa.DateTime(), nullable=True),
    sa.Column('ist_testphase', sa.Boolean(), nullable=True),
    sa.Column('testphase_ende', sa.DateTime(), nullable=True),
    sa.Column('testphase_konvertiert', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gekuendigt_am', sa.DateTime(), nullable=True),
    sa.Column('kuendigung_grund', sa.Text(), nullable=True),
    sa.Column('kuendigung_zum', sa.DateTime(), nullable=True),
    sa.Column('preis_snapshot', sa.Float(), nullable=True),
    sa.Column('preis_modell_snapshot', sa.String(length=20), nullable=True),
    sa.Column('plugin_version_bei_lizenzierung', sa.String(length=20), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plugin_id'], ['plg_plugin.id'], ),
    sa.ForeignKeyConstraint(['preis_id'], ['plg_preis.id'], ),
    sa.ForeignKeyConstraint(['projekt_id'], ['plg_projekt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lizenz_plugin', 'plg_lizenz', ['plugin_id'], unique=False)
    op.create_index('idx_lizenz_projekt', 'plg_lizenz', ['projekt_id'], unique=False)
    op.create_index('idx_lizenz_status', 'plg_lizenz', ['status'], unique=False)
    op.create_index('idx_lizenz_testphase', 'plg_lizenz', ['ist_testphase', 'testphase_ende'], unique=False)
    op.create_table('plg_lizenz_historie',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lizenz_id', sa.String(length=36), nullable=False),
    sa.Column('alter_status', sa.String(length=20), nullable=True),
    sa.Column('neuer_status', sa.String(length=20), nullable=False),
    sa.Column('aenderungsgrund', sa.String(length=255), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('geaendert_von', sa.String(length=36), nullable=True),
    sa.Column('geaendert_von_typ', sa.String(length=20), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lizenz_id'], ['plg_lizenz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historie_datum', 'plg_lizenz_historie', ['erstellt_am'], unique=False)
    op.create_index('idx_historie_lizenz', 'plg_lizenz_historie', ['lizenz_id'], unique=False)
    # Note: alter_column operations removed - SQLite doesn't support ALTER COLUMN
    # The following indexes might already exist, so we wrap them in try/except
    try:
        op.create_index(op.f('ix_com_organisation_kurzname'), 'com_organisation', ['kurzname'], unique=False)
    except Exception:
        pass  # Index might already exist
    try:
        op.create_index(op.f('ix_com_organisation_legacy_id'), 'com_organisation', ['legacy_id'], unique=True)
    except Exception:
        pass  # Index might already exist
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: alter_column operations removed - SQLite doesn't support ALTER COLUMN
    try:
        op.drop_index(op.f('ix_com_organisation_legacy_id'), table_name='com_organisation')
    except Exception:
        pass
    try:
        op.drop_index(op.f('ix_com_organisation_kurzname'), table_name='com_organisation')
    except Exception:
        pass
    op.drop_index('idx_historie_lizenz', table_name='plg_lizenz_historie')
    op.drop_index('idx_historie_datum', table_name='plg_lizenz_historie')
    op.drop_table('plg_lizenz_historie')
    op.drop_index('idx_lizenz_testphase', table_name='plg_lizenz')
    op.drop_index('idx_lizenz_status', table_name='plg_lizenz')
    op.drop_index('idx_lizenz_projekt', table_name='plg_lizenz')
    op.drop_index('idx_lizenz_plugin', table_name='plg_lizenz')
    op.drop_table('plg_lizenz')
    op.drop_index(op.f('ix_plg_projekt_slug'), table_name='plg_projekt')
    op.drop_index(op.f('ix_plg_projekt_kontakt_email'), table_name='plg_projekt')
    op.drop_index(op.f('ix_plg_projekt_api_key_hash'), table_name='plg_projekt')
    op.drop_index('idx_projekt_typ', table_name='plg_projekt')
    op.drop_index('idx_projekt_geo', table_name='plg_projekt')
    op.drop_index('idx_projekt_aktiv', table_name='plg_projekt')
    op.drop_table('plg_projekt')
    op.drop_index('idx_preis_projekttyp', table_name='plg_preis')
    op.drop_index('idx_preis_plugin', table_name='plg_preis')
    op.drop_index('idx_preis_aktiv', table_name='plg_preis')
    op.drop_table('plg_preis')
    op.drop_index('uq_plugin_version', table_name='plg_plugin_version')
    op.drop_index('idx_version_plugin', table_name='plg_plugin_version')
    op.drop_index('idx_version_aktuell', table_name='plg_plugin_version')
    op.drop_table('plg_plugin_version')
    op.drop_index(op.f('ix_plg_plugin_slug'), table_name='plg_plugin')
    op.drop_index('idx_plugin_status', table_name='plg_plugin')
    op.drop_index('idx_plugin_kategorie', table_name='plg_plugin')
    op.drop_table('plg_plugin')
    op.drop_index(op.f('ix_plg_projekttyp_slug'), table_name='plg_projekttyp')
    op.drop_index('idx_projekttyp_sortierung', table_name='plg_projekttyp')
    op.drop_table('plg_projekttyp')
    op.drop_index(op.f('ix_plg_kategorie_slug'), table_name='plg_kategorie')
    op.drop_index('idx_kategorie_sortierung', table_name='plg_kategorie')
    op.drop_table('plg_kategorie')
    # ### end Alembic commands ###
