"""add metadaten and quelldaten to com_unternehmen

Revision ID: 5812571c7269
Revises: 0ec85ea7a1d8
Create Date: 2026-02-17 18:52:24.621903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5812571c7269'
down_revision: Union[str, Sequence[str], None] = '0ec85ea7a1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('com_unternehmen', sa.Column('metadaten', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('com_unternehmen', 'metadaten')
    # ### end Alembic commands ###
