"""add ist_favorit and sortierung to bas_rechtsform and geo_land

Revision ID: 730e037ba158
Revises: f7cce6d39946
Create Date: 2026-02-20 19:33:42.112924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730e037ba158'
down_revision: Union[str, Sequence[str], None] = 'f7cce6d39946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bas_rechtsform', sa.Column('ist_favorit', sa.Boolean(), nullable=True))
    op.add_column('bas_rechtsform', sa.Column('sortierung', sa.Integer(), nullable=True))
    op.add_column('geo_land', sa.Column('ist_favorit', sa.Boolean(), nullable=True))
    op.add_column('geo_land', sa.Column('sortierung', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geo_land', 'sortierung')
    op.drop_column('geo_land', 'ist_favorit')
    op.drop_column('bas_rechtsform', 'sortierung')
    op.drop_column('bas_rechtsform', 'ist_favorit')
    # ### end Alembic commands ###
