"""extend_prod_artikel_multilang_pangv_gpsr

Revision ID: 896f2c2e0235
Revises: fb7fcca19408
Create Date: 2026-02-15 19:25:04.224300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896f2c2e0235'
down_revision: Union[str, Sequence[str], None] = 'fb7fcca19408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prod_artikel', sa.Column('einkaufspreis_netto', sa.Float(), nullable=True))
    op.add_column('prod_artikel', sa.Column('verpackungseinheit', sa.Integer(), nullable=True))
    op.add_column('prod_artikel', sa.Column('rabattfaehig', sa.Boolean(), nullable=True))
    op.add_column('prod_artikel', sa.Column('pangv_einheit', sa.String(length=10), nullable=True))
    op.add_column('prod_artikel', sa.Column('pangv_inhalt', sa.Float(), nullable=True))
    op.add_column('prod_artikel', sa.Column('pangv_grundmenge', sa.Float(), nullable=True))
    op.add_column('prod_artikel', sa.Column('sicherheitssymbol', sa.String(length=20), nullable=True))
    op.add_column('prod_artikel', sa.Column('gpsr_bevollmaechtigter_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'prod_artikel', 'com_unternehmen', ['gpsr_bevollmaechtigter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prod_artikel', type_='foreignkey')
    op.drop_column('prod_artikel', 'gpsr_bevollmaechtigter_id')
    op.drop_column('prod_artikel', 'sicherheitssymbol')
    op.drop_column('prod_artikel', 'pangv_grundmenge')
    op.drop_column('prod_artikel', 'pangv_inhalt')
    op.drop_column('prod_artikel', 'pangv_einheit')
    op.drop_column('prod_artikel', 'rabattfaehig')
    op.drop_column('prod_artikel', 'verpackungseinheit')
    op.drop_column('prod_artikel', 'einkaufspreis_netto')
    # ### end Alembic commands ###
