"""add_maerklin_import_models

Revision ID: b93537e1486f
Revises: a3f7c2e19b45
Create Date: 2026-02-12 19:09:17.564284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93537e1486f'
down_revision: Union[str, Sequence[str], None] = 'a3f7c2e19b45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bas_sprache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_eng', sa.String(length=100), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bas_sprache_code'), 'bas_sprache', ['code'], unique=True)
    op.create_table('com_dienstleistung',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_com_dienstleistung_name'), 'com_dienstleistung', ['name'], unique=True)
    op.create_table('com_bonitaet',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unternehmen_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('quelle', sa.String(length=100), nullable=True),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unternehmen_id'], ['com_unternehmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bonitaet_unternehmen', 'com_bonitaet', ['unternehmen_id'], unique=False)
    op.create_table('com_lieferbeziehung',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unternehmen_id', sa.String(length=36), nullable=False),
    sa.Column('lieferant_id', sa.String(length=36), nullable=False),
    sa.Column('kundennummer', sa.String(length=50), nullable=True),
    sa.Column('store_typ', sa.String(length=20), nullable=True),
    sa.Column('bonus_haendler', sa.Boolean(), nullable=True),
    sa.Column('in_haendlersuche', sa.Boolean(), nullable=True),
    sa.Column('ist_mhi', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lieferant_id'], ['com_unternehmen.id'], ),
    sa.ForeignKeyConstraint(['unternehmen_id'], ['com_unternehmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lieferbeziehung_lieferant', 'com_lieferbeziehung', ['lieferant_id'], unique=False)
    op.create_index('uq_lieferbeziehung', 'com_lieferbeziehung', ['unternehmen_id', 'lieferant_id'], unique=True)
    op.create_table('com_marke',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hersteller_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kurzname', sa.String(length=50), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hersteller_id'], ['com_unternehmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_marke_name', 'com_marke', ['name'], unique=False)
    op.create_index('uq_marke_hersteller_name', 'com_marke', ['hersteller_id', 'name'], unique=True)
    op.create_table('com_unternehmen_dienstleistung',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unternehmen_id', sa.String(length=36), nullable=False),
    sa.Column('dienstleistung_id', sa.String(length=36), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dienstleistung_id'], ['com_dienstleistung.id'], ),
    sa.ForeignKeyConstraint(['unternehmen_id'], ['com_unternehmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ud_unternehmen', 'com_unternehmen_dienstleistung', ['unternehmen_id'], unique=False)
    op.create_index('uq_unternehmen_dienstleistung', 'com_unternehmen_dienstleistung', ['unternehmen_id', 'dienstleistung_id'], unique=True)
    op.create_table('com_serie',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marke_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marke_id'], ['com_marke.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_serie_marke_name', 'com_serie', ['marke_id', 'name'], unique=True)
    op.create_table('com_unternehmen_sortiment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unternehmen_id', sa.String(length=36), nullable=False),
    sa.Column('marke_id', sa.String(length=36), nullable=True),
    sa.Column('serie_id', sa.String(length=36), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marke_id'], ['com_marke.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['com_serie.id'], ),
    sa.ForeignKeyConstraint(['unternehmen_id'], ['com_unternehmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sortiment_marke', 'com_unternehmen_sortiment', ['marke_id'], unique=False)
    op.create_index('idx_sortiment_serie', 'com_unternehmen_sortiment', ['serie_id'], unique=False)
    op.create_index('idx_sortiment_unternehmen', 'com_unternehmen_sortiment', ['unternehmen_id'], unique=False)
    # ComUnternehmen: add new columns
    op.add_column('com_unternehmen', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('com_unternehmen', sa.Column('adresszeile', sa.String(length=500), nullable=True))
    op.add_column('com_unternehmen', sa.Column('email2', sa.String(length=255), nullable=True))
    op.add_column('com_unternehmen', sa.Column('fax', sa.String(length=50), nullable=True))
    op.add_column('com_unternehmen', sa.Column('sprache_id', sa.String(length=36), nullable=True))
    op.create_index('idx_unternehmen_sprache', 'com_unternehmen', ['sprache_id'], unique=False)
    op.create_foreign_key('fk_unternehmen_sprache', 'com_unternehmen', 'bas_sprache', ['sprache_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ComUnternehmen: remove new columns
    op.drop_constraint('fk_unternehmen_sprache', 'com_unternehmen', type_='foreignkey')
    op.drop_index('idx_unternehmen_sprache', table_name='com_unternehmen')
    op.drop_column('com_unternehmen', 'sprache_id')
    op.drop_column('com_unternehmen', 'fax')
    op.drop_column('com_unternehmen', 'email2')
    op.drop_column('com_unternehmen', 'adresszeile')
    op.drop_column('com_unternehmen', 'status')
    # Drop new tables (reverse order of creation)
    op.drop_index('idx_sortiment_unternehmen', table_name='com_unternehmen_sortiment')
    op.drop_index('idx_sortiment_serie', table_name='com_unternehmen_sortiment')
    op.drop_index('idx_sortiment_marke', table_name='com_unternehmen_sortiment')
    op.drop_table('com_unternehmen_sortiment')
    op.drop_index('uq_serie_marke_name', table_name='com_serie')
    op.drop_table('com_serie')
    op.drop_index('uq_unternehmen_dienstleistung', table_name='com_unternehmen_dienstleistung')
    op.drop_index('idx_ud_unternehmen', table_name='com_unternehmen_dienstleistung')
    op.drop_table('com_unternehmen_dienstleistung')
    op.drop_index('uq_marke_hersteller_name', table_name='com_marke')
    op.drop_index('idx_marke_name', table_name='com_marke')
    op.drop_table('com_marke')
    op.drop_index('uq_lieferbeziehung', table_name='com_lieferbeziehung')
    op.drop_index('idx_lieferbeziehung_lieferant', table_name='com_lieferbeziehung')
    op.drop_table('com_lieferbeziehung')
    op.drop_index('idx_bonitaet_unternehmen', table_name='com_bonitaet')
    op.drop_table('com_bonitaet')
    op.drop_index(op.f('ix_com_dienstleistung_name'), table_name='com_dienstleistung')
    op.drop_table('com_dienstleistung')
    op.drop_index(op.f('ix_bas_sprache_code'), table_name='bas_sprache')
    op.drop_table('bas_sprache')
    # ### end Alembic commands ###
