"""Initial schema

Revision ID: bd831a7d434a
Revises: 
Create Date: 2026-01-16 13:01:17.440186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd831a7d434a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_partner', 'kosten_unternehmen_pro_abfrage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('(0.001)'))
    op.alter_column('api_partner', 'zugelassene_laender_ids',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('com_organisation', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_index(op.f('ix_com_organisation_kurzname'), 'com_organisation', ['kurzname'], unique=False)
    op.create_index(op.f('ix_com_organisation_legacy_id'), 'com_organisation', ['legacy_id'], unique=True)
    op.alter_column('com_unternehmen_organisation', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('com_unternehmen_organisation', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_com_organisation_legacy_id'), table_name='com_organisation')
    op.drop_index(op.f('ix_com_organisation_kurzname'), table_name='com_organisation')
    op.alter_column('com_organisation', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('api_partner', 'zugelassene_laender_ids',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(NULL)'))
    op.alter_column('api_partner', 'kosten_unternehmen_pro_abfrage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(0.001)'))
    # ### end Alembic commands ###
