"""add_etl_import_file_and_source_extensions

Revision ID: c671cb46a72b
Revises: d1217812e0e7
Create Date: 2026-02-13 14:21:42.258425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c671cb46a72b'
down_revision: Union[str, Sequence[str], None] = 'd1217812e0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_source', sa.Column('titel', sa.String(length=200), nullable=True))
    op.add_column('etl_source', sa.Column('verantwortlicher', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_source', 'verantwortlicher')
    op.drop_column('etl_source', 'titel')
    # ### end Alembic commands ###
