"""add_profiltext_medien_quelle_vertriebsstruktur

Revision ID: f7cce6d39946
Revises: 376057f71dd5
Create Date: 2026-02-20 16:45:50.209091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7cce6d39946'
down_revision: Union[str, Sequence[str], None] = '376057f71dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('com_quelle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unternehmen_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('beschreibung', sa.String(length=500), nullable=True),
    sa.Column('abrufdatum', sa.Date(), nullable=True),
    sa.Column('quelle_typ', sa.String(length=30), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unternehmen_id'], ['com_unternehmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quelle_unternehmen', 'com_quelle', ['unternehmen_id'], unique=False)
    op.create_index('uq_quelle_url', 'com_quelle', ['unternehmen_id', 'url'], unique=True)
    op.create_table('com_vertriebsstruktur',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hersteller_id', sa.String(length=36), nullable=False),
    sa.Column('lieferant_id', sa.String(length=36), nullable=False),
    sa.Column('rolle', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('ist_empfohlen', sa.Boolean(), nullable=True),
    sa.Column('empfehlung_text', sa.Text(), nullable=True),
    sa.Column('sortierung', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hersteller_id'], ['com_unternehmen.id'], ),
    sa.ForeignKeyConstraint(['lieferant_id'], ['com_unternehmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vertrieb_hersteller', 'com_vertriebsstruktur', ['hersteller_id'], unique=False)
    op.create_index('idx_vertrieb_lieferant', 'com_vertriebsstruktur', ['lieferant_id'], unique=False)
    op.create_index('uq_vertrieb_hersteller_lieferant_region', 'com_vertriebsstruktur', ['hersteller_id', 'lieferant_id', 'region'], unique=True)
    op.create_table('com_medien',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unternehmen_id', sa.String(length=36), nullable=True),
    sa.Column('marke_id', sa.String(length=36), nullable=True),
    sa.Column('medienart', sa.String(length=20), nullable=False),
    sa.Column('dateiname', sa.String(length=200), nullable=True),
    sa.Column('dateiformat', sa.String(length=10), nullable=True),
    sa.Column('url_quelle', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('sortierung', sa.Integer(), nullable=True),
    sa.Column('ist_heruntergeladen', sa.Boolean(), nullable=True),
    sa.Column('download_fehler', sa.String(length=500), nullable=True),
    sa.Column('lizenz_id', sa.String(length=36), nullable=True),
    sa.Column('lizenz_hinweis', sa.String(length=500), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lizenz_id'], ['bas_medien_lizenz.id'], ),
    sa.ForeignKeyConstraint(['marke_id'], ['com_marke.id'], ),
    sa.ForeignKeyConstraint(['unternehmen_id'], ['com_unternehmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_medien_art', 'com_medien', ['medienart'], unique=False)
    op.create_index('idx_medien_lizenz', 'com_medien', ['lizenz_id'], unique=False)
    op.create_index('idx_medien_marke', 'com_medien', ['marke_id'], unique=False)
    op.create_index('idx_medien_unternehmen', 'com_medien', ['unternehmen_id'], unique=False)
    op.create_table('com_profiltext',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('unternehmen_id', sa.String(length=36), nullable=True),
    sa.Column('marke_id', sa.String(length=36), nullable=True),
    sa.Column('serie_id', sa.String(length=36), nullable=True),
    sa.Column('typ', sa.String(length=10), nullable=False),
    sa.Column('sprache', sa.String(length=5), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('quelle', sa.String(length=50), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marke_id'], ['com_marke.id'], ),
    sa.ForeignKeyConstraint(['serie_id'], ['com_serie.id'], ),
    sa.ForeignKeyConstraint(['unternehmen_id'], ['com_unternehmen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profiltext_marke', 'com_profiltext', ['marke_id'], unique=False)
    op.create_index('idx_profiltext_serie', 'com_profiltext', ['serie_id'], unique=False)
    op.create_index('idx_profiltext_unternehmen', 'com_profiltext', ['unternehmen_id'], unique=False)
    op.create_index('uq_profiltext_marke', 'com_profiltext', ['marke_id', 'sprache', 'typ'], unique=True, postgresql_where='marke_id IS NOT NULL')
    op.create_index('uq_profiltext_serie', 'com_profiltext', ['serie_id', 'sprache', 'typ'], unique=True, postgresql_where='serie_id IS NOT NULL')
    op.create_index('uq_profiltext_unternehmen', 'com_profiltext', ['unternehmen_id', 'sprache', 'typ'], unique=True, postgresql_where='unternehmen_id IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_profiltext_unternehmen', table_name='com_profiltext', postgresql_where='unternehmen_id IS NOT NULL')
    op.drop_index('uq_profiltext_serie', table_name='com_profiltext', postgresql_where='serie_id IS NOT NULL')
    op.drop_index('uq_profiltext_marke', table_name='com_profiltext', postgresql_where='marke_id IS NOT NULL')
    op.drop_index('idx_profiltext_unternehmen', table_name='com_profiltext')
    op.drop_index('idx_profiltext_serie', table_name='com_profiltext')
    op.drop_index('idx_profiltext_marke', table_name='com_profiltext')
    op.drop_table('com_profiltext')
    op.drop_index('idx_medien_unternehmen', table_name='com_medien')
    op.drop_index('idx_medien_marke', table_name='com_medien')
    op.drop_index('idx_medien_lizenz', table_name='com_medien')
    op.drop_index('idx_medien_art', table_name='com_medien')
    op.drop_table('com_medien')
    op.drop_index('uq_vertrieb_hersteller_lieferant_region', table_name='com_vertriebsstruktur')
    op.drop_index('idx_vertrieb_lieferant', table_name='com_vertriebsstruktur')
    op.drop_index('idx_vertrieb_hersteller', table_name='com_vertriebsstruktur')
    op.drop_table('com_vertriebsstruktur')
    op.drop_index('uq_quelle_url', table_name='com_quelle')
    op.drop_index('idx_quelle_unternehmen', table_name='com_quelle')
    op.drop_table('com_quelle')
    # ### end Alembic commands ###
