"""add_source_field_aliases_to_field_mapping

Revision ID: fb7fcca19408
Revises: c671cb46a72b
Create Date: 2026-02-13 16:16:47.955265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7fcca19408'
down_revision: Union[str, Sequence[str], None] = 'c671cb46a72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_field_mapping', sa.Column('source_field_aliases', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etl_field_mapping', 'source_field_aliases')
    # ### end Alembic commands ###
