# Generated by Django 5.1.1 on 2025-05-07 14:14

import django.core.validators
import django.db.models.deletion
import pim.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0028_alter_bild_bild"),
        ("com", "0037_alter_unternehmenansprechpartner_unternehmen"),
        ("countries_plus", "0005_auto_20160224_1804"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mehrwertsteuer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land",
                    models.CharField(
                        help_text="ISO-Code des Landes (z.B. DE für Deutschland)",
                        max_length=2,
                    ),
                ),
                (
                    "steuersatz",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Mehrwertsteuersatz in Prozent",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "MwSt",
                "verbose_name_plural": "MwSt",
            },
        ),
        migrations.CreateModel(
            name="Produkteigenschaft",
            fields=[
                ("name_de", models.CharField(max_length=100, verbose_name="Name (DE)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (EN)"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (FR)"
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (NL)"
                    ),
                ),
                (
                    "name_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (IT)"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (ES)"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Eigenschaftscode"
                    ),
                ),
                (
                    "ist_pflicht",
                    models.BooleanField(default=False, verbose_name="Pflichtfeld"),
                ),
                (
                    "mehrfach_erlaubt",
                    models.BooleanField(
                        default=False, verbose_name="Mehrfachwerte erlaubt"
                    ),
                ),
                (
                    "filterbar",
                    models.BooleanField(default=False, verbose_name="Filterbar"),
                ),
                (
                    "anzeige_reihenfolge",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Anzeige-Reihenfolge"
                    ),
                ),
                (
                    "daten_typ",
                    models.CharField(
                        choices=[
                            ("TEXT", "Freitext"),
                            ("INT", "Ganze Zahl"),
                            ("DECIMAL", "Dezimalzahl"),
                            ("BOOL", "Ja/Nein"),
                            ("DATUM", "Datum"),
                            ("STANDARD_REF", "Verweis (Standard)"),
                            ("BAHNVERWALTUNG_REF", "Verweis (Bahnverwaltung)"),
                            ("NENNGR_REF", "Verweis (Nenngröße)"),
                        ],
                        max_length=30,
                        verbose_name="Datentyp",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RefMobaNenngroesse",
            fields=[
                ("name_de", models.CharField(max_length=100, verbose_name="Name (DE)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (EN)"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (FR)"
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (NL)"
                    ),
                ),
                (
                    "name_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (IT)"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (ES)"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("spurweite_mm", models.FloatField(verbose_name="Spurweite (mm)")),
                ("maßstab", models.CharField(max_length=20, verbose_name="Maßstab")),
                (
                    "kommentar",
                    models.TextField(blank=True, null=True, verbose_name="Kommentar"),
                ),
            ],
            options={
                "verbose_name": "Eigenschaft Moba Nenngrößen",
                "verbose_name_plural": "Eigenschaften Moba Nenngrößen",
            },
        ),
        migrations.CreateModel(
            name="TaxoProduktgruppe",
            fields=[
                ("name_de", models.CharField(max_length=100, verbose_name="Name (DE)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (EN)"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (FR)"
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (NL)"
                    ),
                ),
                (
                    "name_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (IT)"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (ES)"
                    ),
                ),
                (
                    "alias_de",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (DE)",
                    ),
                ),
                (
                    "alias_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (EN)",
                    ),
                ),
                (
                    "alias_fr",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (FR)",
                    ),
                ),
                (
                    "alias_nl",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (NL)",
                    ),
                ),
                (
                    "alias_it",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (IT)",
                    ),
                ),
                (
                    "alias_es",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (ES)",
                    ),
                ),
                (
                    "langtext_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (DE)"
                    ),
                ),
                (
                    "langtext_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (EN)"
                    ),
                ),
                (
                    "langtext_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (FR)"
                    ),
                ),
                (
                    "langtext_nl",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (NL)"
                    ),
                ),
                (
                    "langtext_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (IT)"
                    ),
                ),
                (
                    "langtext_es",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (ES)"
                    ),
                ),
                (
                    "zusatztext_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (DE)"
                    ),
                ),
                (
                    "zusatztext_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (EN)"
                    ),
                ),
                (
                    "zusatztext_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (FR)"
                    ),
                ),
                (
                    "zusatztext_nl",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (NL)"
                    ),
                ),
                (
                    "zusatztext_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (IT)"
                    ),
                ),
                (
                    "zusatztext_es",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (ES)"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=2, verbose_name="Produktgruppen-Code"),
                ),
                (
                    "gpc_classcode",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="GPC Class-Code",
                    ),
                ),
                (
                    "gpc_classprio",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="GPC Class-Prio",
                    ),
                ),
                (
                    "gpc_classtitel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="GPC Class-Titel",
                    ),
                ),
                (
                    "gpc_brickcode",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="GPC Brick-Code",
                    ),
                ),
                (
                    "gpc_brickprio",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="GPC Brick-Prio",
                    ),
                ),
                (
                    "gpc_bricktitel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="GPC Brick-Titel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxonomie (3) Produktgruppe",
                "verbose_name_plural": "Taxonomien (3) Produktgruppen",
            },
        ),
        migrations.CreateModel(
            name="TaxoProduktwelt",
            fields=[
                ("name_de", models.CharField(max_length=100, verbose_name="Name (DE)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (EN)"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (FR)"
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (NL)"
                    ),
                ),
                (
                    "name_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (IT)"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (ES)"
                    ),
                ),
                (
                    "alias_de",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (DE)",
                    ),
                ),
                (
                    "alias_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (EN)",
                    ),
                ),
                (
                    "alias_fr",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (FR)",
                    ),
                ),
                (
                    "alias_nl",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (NL)",
                    ),
                ),
                (
                    "alias_it",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (IT)",
                    ),
                ),
                (
                    "alias_es",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (ES)",
                    ),
                ),
                (
                    "langtext_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (DE)"
                    ),
                ),
                (
                    "langtext_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (EN)"
                    ),
                ),
                (
                    "langtext_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (FR)"
                    ),
                ),
                (
                    "langtext_nl",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (NL)"
                    ),
                ),
                (
                    "langtext_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (IT)"
                    ),
                ),
                (
                    "langtext_es",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (ES)"
                    ),
                ),
                (
                    "zusatztext_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (DE)"
                    ),
                ),
                (
                    "zusatztext_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (EN)"
                    ),
                ),
                (
                    "zusatztext_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (FR)"
                    ),
                ),
                (
                    "zusatztext_nl",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (NL)"
                    ),
                ),
                (
                    "zusatztext_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (IT)"
                    ),
                ),
                (
                    "zusatztext_es",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (ES)"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=2, verbose_name="Produktwelt-Code"),
                ),
                (
                    "gpc_classcode",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="GPC Class-Code",
                    ),
                ),
                (
                    "gpc_classprio",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="GPC Class-Prio",
                    ),
                ),
                (
                    "gpc_classtitel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="GPC Class-Titel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxonomie (2) Produktwelt",
                "verbose_name_plural": "Taxonomien (2) Produktwelten",
            },
        ),
        migrations.CreateModel(
            name="WG_BambergerCode",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="Der Bamberger Code ist ein veraltetes, aber verbreitetes Warenklassifikationssystem",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Bamberger Code",
                    ),
                ),
                (
                    "bezeichnung",
                    models.CharField(
                        help_text="Bezeichnung der Warengruppe",
                        max_length=255,
                        verbose_name="Warengruppe Bezeichnung",
                    ),
                ),
                (
                    "beschreibung",
                    models.TextField(
                        help_text="Beschreibung der Warengruppe",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "warenbereich",
                    models.PositiveIntegerField(
                        help_text="Warenbereich (Werte von 1 bis 9)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9),
                        ],
                        verbose_name="Warenbereich",
                    ),
                ),
                (
                    "warenbereich_bezeichnung",
                    models.CharField(
                        help_text="Bezeichnung des Warenbereichs",
                        max_length=255,
                        verbose_name="Warenbereich Bezeichnung",
                    ),
                ),
                (
                    "gs1_klassifikation",
                    models.CharField(
                        blank=True,
                        help_text="Warenklassifikation der GS1 (hilfsweise)",
                        max_length=255,
                        null=True,
                        verbose_name="GS1 Klassifikation",
                    ),
                ),
            ],
            options={
                "verbose_name": "WG Bamberger Vz.",
                "verbose_name_plural": "WG Bamberger Vz.",
            },
        ),
        migrations.CreateModel(
            name="Produkt",
            fields=[
                (
                    "erstellt_am",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "geaendert_am",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Geändert am"
                    ),
                ),
                (
                    "softgeloescht_am",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Soft gelöscht am"
                    ),
                ),
                (
                    "softgeloescht",
                    models.BooleanField(default=False, verbose_name="Soft gelöscht"),
                ),
                (
                    "geaendert_bemerkung",
                    models.TextField(
                        blank=True, null=True, verbose_name="Geändert Bemerkung"
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bezeichnung",
                    pim.fields.PimCharField(
                        help_text="Bezeichnung des Artikels ohne Markenname oder Herstellerartikelnummer",
                        max_length=255,
                        ntg_ref="NTG-P-015",
                    ),
                ),
                (
                    "rabattgruppe_buschdata",
                    pim.fields.PimCharField(
                        blank=True,
                        help_text="Rabattgruppe für BuschData",
                        max_length=1,
                        ntg_ref="NTG-P-314",
                        null=True,
                        verbose_name="Rabattgruppe BuschData",
                    ),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        default="2",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="erstellt_von_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "geaendert_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geaendert_von_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "hersteller",
                    pim.fields.PimForeignKey(
                        blank=True,
                        help_text="Verknüpfung zum Hersteller des Artikels",
                        ntg_ref="NTG-P-003",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="com.unternehmen",
                    ),
                ),
                (
                    "saison",
                    pim.fields.PimForeignKey(
                        blank=True,
                        help_text="Saisonkennzeichnung des Artikels",
                        limit_choices_to={
                            "auswahl_gruppe__gruppe": "Saisonkennzeichnung"
                        },
                        ntg_ref="NTG-P-146",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.auswahlschluesselliste",
                        verbose_name="Saisonkennzeichen",
                    ),
                ),
                (
                    "softgeloescht_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="softgeloescht_von_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Soft gelöscht von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkt",
            },
        ),
        migrations.CreateModel(
            name="Produkt_Identifikation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wert",
                    models.CharField(max_length=255, verbose_name="Schlüsselwert"),
                ),
                (
                    "produkt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifikationen",
                        to="pim.produkt",
                    ),
                ),
                (
                    "schluessel",
                    models.ForeignKey(
                        limit_choices_to={"gruppe": "ArtikelIdentifikation"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.auswahlschluesselliste",
                        verbose_name="Identifikationsschlüssel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt-Identifikation",
                "verbose_name_plural": "Produkt-Identifikationen",
            },
        ),
        migrations.CreateModel(
            name="Produkt_Lieferant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lieferantartnr",
                    models.CharField(
                        help_text="Artikelnummer des Lieferanten", max_length=35
                    ),
                ),
                (
                    "lieferant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lieferungen",
                        to="com.unternehmen",
                    ),
                ),
                (
                    "produkt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lieferanten",
                        to="pim.produkt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produkt_Mehrwertsteuer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "land_hilfsweise",
                    models.CharField(
                        help_text="ISO-Code des Landes (z.B. DE für Deutschland)",
                        max_length=2,
                    ),
                ),
                (
                    "mehrwertsteuersatz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pim.mehrwertsteuer",
                    ),
                ),
                (
                    "produkt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pim.produkt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProdukteigenschaftValidierungsregel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "regel",
                    models.TextField(verbose_name="Regel (als Ausdruck oder JSON)"),
                ),
                (
                    "fehlermeldung",
                    models.CharField(max_length=255, verbose_name="Fehlermeldung"),
                ),
                (
                    "aktiv",
                    models.BooleanField(default=True, verbose_name="Regel aktiv"),
                ),
                (
                    "produkteigenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validierungsregeln",
                        to="pim.produkteigenschaft",
                        verbose_name="Produkteigenschaft",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefMobaBahnverwaltung",
            fields=[
                ("name_de", models.CharField(max_length=100, verbose_name="Name (DE)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (EN)"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (FR)"
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (NL)"
                    ),
                ),
                (
                    "name_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (IT)"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (ES)"
                    ),
                ),
                (
                    "langtext_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (DE)"
                    ),
                ),
                (
                    "langtext_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (EN)"
                    ),
                ),
                (
                    "langtext_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (FR)"
                    ),
                ),
                (
                    "langtext_nl",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (NL)"
                    ),
                ),
                (
                    "langtext_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (IT)"
                    ),
                ),
                (
                    "langtext_es",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (ES)"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kuerzel",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Kürzel"
                    ),
                ),
                (
                    "gruendungsjahr",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1750),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                        verbose_name="Gründungsjahr",
                    ),
                ),
                (
                    "epoche_i",
                    models.BooleanField(default=False, verbose_name="Epoche I"),
                ),
                (
                    "epoche_ii",
                    models.BooleanField(default=False, verbose_name="Epoche II"),
                ),
                (
                    "epoche_iii",
                    models.BooleanField(default=False, verbose_name="Epoche III"),
                ),
                (
                    "epoche_iv",
                    models.BooleanField(default=False, verbose_name="Epoche IV"),
                ),
                (
                    "epoche_v",
                    models.BooleanField(default=False, verbose_name="Epoche V"),
                ),
                (
                    "epoche_vi",
                    models.BooleanField(default=False, verbose_name="Epoche VI"),
                ),
                (
                    "aenderungsjahr",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1750),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                        verbose_name="Änderungsjahr",
                    ),
                ),
                (
                    "aenderungs_beschreibung",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Einstellung", "Einstellung"),
                            ("Umbenennung", "Umbenennung"),
                            ("Umfirmierung", "Umfirmierung"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Änderungsbeschreibung",
                    ),
                ),
                (
                    "land",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="countries_plus.country",
                        verbose_name="Land",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eigenschaft Moba Bahnverwaltung",
                "verbose_name_plural": "Eigenschaften Moba Bahnverwaltungen",
            },
        ),
        migrations.CreateModel(
            name="RefStandardWert",
            fields=[
                ("name_de", models.CharField(max_length=100, verbose_name="Name (DE)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (EN)"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (FR)"
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (NL)"
                    ),
                ),
                (
                    "name_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (IT)"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (ES)"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("typ", models.CharField(max_length=50, verbose_name="Referenztyp")),
                ("code", models.CharField(max_length=50, verbose_name="Wert-Code")),
            ],
            options={
                "verbose_name": "Eigenschaft Standard",
                "verbose_name_plural": "Eigenschaften Standard",
                "unique_together": {("typ", "code")},
            },
        ),
        migrations.CreateModel(
            name="ProduktEigenschaftswert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "freitext_wert",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Freitextwert",
                    ),
                ),
                (
                    "ganzzahl_wert",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ganzzahlwert"
                    ),
                ),
                (
                    "dezimal_wert",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Dezimalwert",
                    ),
                ),
                (
                    "bool_wert",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Boolescher Wert"
                    ),
                ),
                (
                    "datum_wert",
                    models.DateField(blank=True, null=True, verbose_name="Datumswert"),
                ),
                (
                    "produkt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eigenschaftswerte",
                        to="pim.produkt",
                        verbose_name="Produkt",
                    ),
                ),
                (
                    "produkteigenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produktwerte",
                        to="pim.produkteigenschaft",
                        verbose_name="Produkteigenschaft",
                    ),
                ),
                (
                    "bahnverw_ref_wert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pim.refmobabahnverwaltung",
                        verbose_name="Bahnverwaltung-Referenzwert",
                    ),
                ),
                (
                    "nenngroesse_ref_wert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pim.refmobanenngroesse",
                        verbose_name="Nenngröße-Referenzwert",
                    ),
                ),
                (
                    "standard_ref_wert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pim.refstandardwert",
                        verbose_name="Standard-Referenzwert",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Taxonomie",
            fields=[
                (
                    "erstellt_am",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "geaendert_am",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Geändert am"
                    ),
                ),
                (
                    "softgeloescht_am",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Soft gelöscht am"
                    ),
                ),
                (
                    "softgeloescht",
                    models.BooleanField(default=False, verbose_name="Soft gelöscht"),
                ),
                (
                    "geaendert_bemerkung",
                    models.TextField(
                        blank=True, null=True, verbose_name="Geändert Bemerkung"
                    ),
                ),
                ("aktiv", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Taxonomie-Bezeichnung",
                    ),
                ),
                (
                    "erstellt_von",
                    models.ForeignKey(
                        default="2",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="erstellt_von_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Erstellt von",
                    ),
                ),
                (
                    "geaendert_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geaendert_von_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Geändert von",
                    ),
                ),
                (
                    "softgeloescht_von",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="softgeloescht_von_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Soft gelöscht von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxonomie",
                "verbose_name_plural": "Taxonomien",
            },
        ),
        migrations.CreateModel(
            name="TaxoProduktkategorie",
            fields=[
                ("name_de", models.CharField(max_length=100, verbose_name="Name (DE)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (EN)"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (FR)"
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (NL)"
                    ),
                ),
                (
                    "name_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (IT)"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (ES)"
                    ),
                ),
                (
                    "alias_de",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (DE)",
                    ),
                ),
                (
                    "alias_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (EN)",
                    ),
                ),
                (
                    "alias_fr",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (FR)",
                    ),
                ),
                (
                    "alias_nl",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (NL)",
                    ),
                ),
                (
                    "alias_it",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (IT)",
                    ),
                ),
                (
                    "alias_es",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (ES)",
                    ),
                ),
                (
                    "langtext_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (DE)"
                    ),
                ),
                (
                    "langtext_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (EN)"
                    ),
                ),
                (
                    "langtext_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (FR)"
                    ),
                ),
                (
                    "langtext_nl",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (NL)"
                    ),
                ),
                (
                    "langtext_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (IT)"
                    ),
                ),
                (
                    "langtext_es",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (ES)"
                    ),
                ),
                (
                    "zusatztext_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (DE)"
                    ),
                ),
                (
                    "zusatztext_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (EN)"
                    ),
                ),
                (
                    "zusatztext_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (FR)"
                    ),
                ),
                (
                    "zusatztext_nl",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (NL)"
                    ),
                ),
                (
                    "zusatztext_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (IT)"
                    ),
                ),
                (
                    "zusatztext_es",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (ES)"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2, verbose_name="Produktkategorie-Code"
                    ),
                ),
                (
                    "gpc_brickcode",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="GPC Brick-Code",
                    ),
                ),
                (
                    "gpc_brickprio",
                    models.CharField(
                        blank=True,
                        max_length=1,
                        null=True,
                        verbose_name="GPC Brick-Prio",
                    ),
                ),
                (
                    "gpc_bricktitel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="GPC Brick-Titel",
                    ),
                ),
                (
                    "produktgruppe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produktkategorien",
                        to="pim.taxoproduktgruppe",
                        verbose_name="Produktgruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxonomie (4) Produktkategorie",
                "verbose_name_plural": "Taxonomien (4) Produktkategorien",
            },
        ),
        migrations.AddField(
            model_name="produkt",
            name="hauptkategorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hauptprodukte",
                to="pim.taxoproduktkategorie",
                verbose_name="Hauptkategorie",
            ),
        ),
        migrations.AddField(
            model_name="produkt",
            name="weitere_kategorien",
            field=models.ManyToManyField(
                blank=True,
                related_name="produkte",
                to="pim.taxoproduktkategorie",
                verbose_name="Weitere Kategorien",
            ),
        ),
        migrations.AddField(
            model_name="taxoproduktgruppe",
            name="produktwelt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produktgruppen",
                to="pim.taxoproduktwelt",
                verbose_name="Produktwelt",
            ),
        ),
        migrations.CreateModel(
            name="TaxoSortiment",
            fields=[
                ("name_de", models.CharField(max_length=100, verbose_name="Name (DE)")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (EN)"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (FR)"
                    ),
                ),
                (
                    "name_nl",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (NL)"
                    ),
                ),
                (
                    "name_it",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (IT)"
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Name (ES)"
                    ),
                ),
                (
                    "alias_de",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (DE)",
                    ),
                ),
                (
                    "alias_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (EN)",
                    ),
                ),
                (
                    "alias_fr",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (FR)",
                    ),
                ),
                (
                    "alias_nl",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (NL)",
                    ),
                ),
                (
                    "alias_it",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (IT)",
                    ),
                ),
                (
                    "alias_es",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Aliase kommasepariert (ES)",
                    ),
                ),
                (
                    "langtext_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (DE)"
                    ),
                ),
                (
                    "langtext_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (EN)"
                    ),
                ),
                (
                    "langtext_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (FR)"
                    ),
                ),
                (
                    "langtext_nl",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (NL)"
                    ),
                ),
                (
                    "langtext_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (IT)"
                    ),
                ),
                (
                    "langtext_es",
                    models.TextField(
                        blank=True, null=True, verbose_name="Langtext (ES)"
                    ),
                ),
                (
                    "zusatztext_de",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (DE)"
                    ),
                ),
                (
                    "zusatztext_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (EN)"
                    ),
                ),
                (
                    "zusatztext_fr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (FR)"
                    ),
                ),
                (
                    "zusatztext_nl",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (NL)"
                    ),
                ),
                (
                    "zusatztext_it",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (IT)"
                    ),
                ),
                (
                    "zusatztext_es",
                    models.TextField(
                        blank=True, null=True, verbose_name="Zusatztext (ES)"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=2, verbose_name="Sortiments-Code"),
                ),
                (
                    "prioritaet",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C")],
                        default="A",
                        max_length=1,
                        verbose_name="Priorität",
                    ),
                ),
                (
                    "gpc_segmentcode",
                    models.CharField(
                        blank=True,
                        help_text="Ein GPC Segment-Code ist die oberste Ebene der Global Product Classification (GPC) von GS1 und bezeichnet einen spezifischen Industriebereich in Form eines 8-stelligen Codes.",
                        max_length=8,
                        null=True,
                        verbose_name="GPC Segment-Code",
                    ),
                ),
                (
                    "gpc_segmenttitel",
                    models.CharField(
                        blank=True,
                        help_text="Ein GPC Segment-Titel ist die oberste Ebene der Global Product Classification (GPC) von GS1 und bezeichnet einen spezifischen Industriebereich, wie z.\u202fB. Lebensmittel&Getränke.",
                        max_length=255,
                        null=True,
                        verbose_name="GPC Segment-Titel",
                    ),
                ),
                (
                    "taxonomie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sortimente",
                        to="pim.taxonomie",
                        verbose_name="Taxonomie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxonomie (1) Sortiment",
                "verbose_name_plural": "Taxonomien (1) Sortimente",
            },
        ),
        migrations.AddField(
            model_name="taxoproduktwelt",
            name="sortiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produktwelten",
                to="pim.taxosortiment",
                verbose_name="Sortiment",
            ),
        ),
        migrations.AddField(
            model_name="produkt",
            name="bamberger_code",
            field=pim.fields.PimForeignKey(
                blank=True,
                help_text="Warengruppe nach Bamberger Code",
                ntg_ref="NTG-P-008",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pim.wg_bambergercode",
            ),
        ),
        migrations.CreateModel(
            name="ProduktkategorieProdukteigenschaft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anzeige_reihenfolge",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Anzeige-Reihenfolge (Override)",
                    ),
                ),
                (
                    "ist_pflicht",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Pflicht (Override)"
                    ),
                ),
                (
                    "produkteigenschaft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kategorien",
                        to="pim.produkteigenschaft",
                        verbose_name="Produkteigenschaft",
                    ),
                ),
                (
                    "kategorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produkteigenschaften",
                        to="pim.taxoproduktkategorie",
                        verbose_name="Produktkategorie",
                    ),
                ),
            ],
            options={
                "unique_together": {("kategorie", "produkteigenschaft")},
            },
        ),
    ]
