# Generated by Django 5.0.14 on 2025-06-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0032_remove_importgooglesheet_sheet_link_and_more"),
        ("pim", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produkt_identifikation",
            name="schluessel",
            field=models.ForeignKey(
                limit_choices_to={"auswahl_gruppe__gruppe": "Artikel Identifikation"},
                on_delete=django.db.models.deletion.CASCADE,
                to="base.auswahlschluesselliste",
                verbose_name="Identifikationsschlüssel",
            ),
        ),
    ]
