# Generated by Django 5.0.14 on 2025-08-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pim", "0003_rename_langtext_de_refmobabahnverwaltung_text_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refmobabahnverwaltung",
            name="text_de",
            field=models.TextField(blank=True, null=True, verbose_name="Text (DE)"),
        ),
        migrations.AlterField(
            model_name="refmobabahnverwaltung",
            name="text_en",
            field=models.TextField(blank=True, null=True, verbose_name="Text (EN)"),
        ),
        migrations.AlterField(
            model_name="refmobabahnverwaltung",
            name="text_es",
            field=models.TextField(blank=True, null=True, verbose_name="Text (ES)"),
        ),
        migrations.AlterField(
            model_name="refmobabahnverwaltung",
            name="text_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Text (FR)"),
        ),
        migrations.AlterField(
            model_name="refmobabahnverwaltung",
            name="text_it",
            field=models.TextField(blank=True, null=True, verbose_name="Text (IT)"),
        ),
        migrations.AlterField(
            model_name="refmobabahnverwaltung",
            name="text_nl",
            field=models.TextField(blank=True, null=True, verbose_name="Text (NL)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktgruppe",
            name="text_de",
            field=models.TextField(blank=True, null=True, verbose_name="Text (DE)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktgruppe",
            name="text_en",
            field=models.TextField(blank=True, null=True, verbose_name="Text (EN)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktgruppe",
            name="text_es",
            field=models.TextField(blank=True, null=True, verbose_name="Text (ES)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktgruppe",
            name="text_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Text (FR)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktgruppe",
            name="text_it",
            field=models.TextField(blank=True, null=True, verbose_name="Text (IT)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktgruppe",
            name="text_nl",
            field=models.TextField(blank=True, null=True, verbose_name="Text (NL)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktkategorie",
            name="text_de",
            field=models.TextField(blank=True, null=True, verbose_name="Text (DE)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktkategorie",
            name="text_en",
            field=models.TextField(blank=True, null=True, verbose_name="Text (EN)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktkategorie",
            name="text_es",
            field=models.TextField(blank=True, null=True, verbose_name="Text (ES)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktkategorie",
            name="text_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Text (FR)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktkategorie",
            name="text_it",
            field=models.TextField(blank=True, null=True, verbose_name="Text (IT)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktkategorie",
            name="text_nl",
            field=models.TextField(blank=True, null=True, verbose_name="Text (NL)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktwelt",
            name="text_de",
            field=models.TextField(blank=True, null=True, verbose_name="Text (DE)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktwelt",
            name="text_en",
            field=models.TextField(blank=True, null=True, verbose_name="Text (EN)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktwelt",
            name="text_es",
            field=models.TextField(blank=True, null=True, verbose_name="Text (ES)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktwelt",
            name="text_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Text (FR)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktwelt",
            name="text_it",
            field=models.TextField(blank=True, null=True, verbose_name="Text (IT)"),
        ),
        migrations.AlterField(
            model_name="taxoproduktwelt",
            name="text_nl",
            field=models.TextField(blank=True, null=True, verbose_name="Text (NL)"),
        ),
        migrations.AlterField(
            model_name="taxosortiment",
            name="text_de",
            field=models.TextField(blank=True, null=True, verbose_name="Text (DE)"),
        ),
        migrations.AlterField(
            model_name="taxosortiment",
            name="text_en",
            field=models.TextField(blank=True, null=True, verbose_name="Text (EN)"),
        ),
        migrations.AlterField(
            model_name="taxosortiment",
            name="text_es",
            field=models.TextField(blank=True, null=True, verbose_name="Text (ES)"),
        ),
        migrations.AlterField(
            model_name="taxosortiment",
            name="text_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Text (FR)"),
        ),
        migrations.AlterField(
            model_name="taxosortiment",
            name="text_it",
            field=models.TextField(blank=True, null=True, verbose_name="Text (IT)"),
        ),
        migrations.AlterField(
            model_name="taxosortiment",
            name="text_nl",
            field=models.TextField(blank=True, null=True, verbose_name="Text (NL)"),
        ),
    ]
